import { ShipSizeEnum, ShipT } from '@/lib/types/ship.type';

export const bot: Array<ShipT[]> = [
  [
    {
      position: { x: 1, y: 3 },
      direction: true,
      type: ShipSizeEnum.XL,
      length: 4,
    },
    {
      position: { x: 4, y: 2 },
      direction: false,
      type: ShipSizeEnum.L,
      length: 3,
    },
    {
      position: { x: 5, y: 8 },
      direction: false,
      type: ShipSizeEnum.L,
      length: 3,
    },
    {
      position: { x: 1, y: 0 },
      direction: true,
      type: ShipSizeEnum.M,
      length: 2,
    },
    {
      position: { x: 7, y: 4 },
      direction: true,
      type: ShipSizeEnum.M,
      length: 2,
    },
    {
      position: { x: 2, y: 8 },
      direction: true,
      type: ShipSizeEnum.M,
      length: 2,
    },
    {
      position: { x: 9, y: 3 },
      direction: false,
      type: ShipSizeEnum.S,
      length: 1,
    },
    {
      position: { x: 0, y: 8 },
      direction: false,
      type: ShipSizeEnum.S,
      length: 1,
    },
    {
      position: { x: 3, y: 0 },
      direction: true,
      type: ShipSizeEnum.S,
      length: 1,
    },
    {
      position: { x: 9, y: 0 },
      direction: true,
      type: ShipSizeEnum.S,
      length: 1,
    },
  ],
  [
    {
      position: { x: 2, y: 3 },
      direction: true,
      type: ShipSizeEnum.XL,
      length: 4,
    },
    {
      position: { x: 1, y: 9 },
      direction: false,
      type: ShipSizeEnum.L,
      length: 3,
    },
    {
      position: { x: 5, y: 5 },
      direction: true,
      type: ShipSizeEnum.L,
      length: 3,
    },
    {
      position: { x: 9, y: 2 },
      direction: true,
      type: ShipSizeEnum.M,
      length: 2,
    },
    {
      position: { x: 4, y: 1 },
      direction: false,
      type: ShipSizeEnum.M,
      length: 2,
    },
    {
      position: { x: 4, y: 3 },
      direction: false,
      type: ShipSizeEnum.M,
      length: 2,
    },
    {
      position: { x: 6, y: 9 },
      direction: false,
      type: ShipSizeEnum.S,
      length: 1,
    },
    {
      position: { x: 8, y: 0 },
      direction: true,
      type: ShipSizeEnum.S,
      length: 1,
    },
    {
      position: { x: 0, y: 2 },
      direction: false,
      type: ShipSizeEnum.S,
      length: 1,
    },
    {
      position: { x: 2, y: 1 },
      direction: false,
      type: ShipSizeEnum.S,
      length: 1,
    },
  ],
  [
    {
      position: { x: 2, y: 4 },
      direction: false,
      type: ShipSizeEnum.XL,
      length: 4,
    },
    {
      position: { x: 7, y: 5 },
      direction: false,
      type: ShipSizeEnum.L,
      length: 3,
    },
    {
      position: { x: 5, y: 2 },
      direction: false,
      type: ShipSizeEnum.L,
      length: 3,
    },
    {
      position: { x: 3, y: 0 },
      direction: true,
      type: ShipSizeEnum.M,
      length: 2,
    },
    {
      position: { x: 0, y: 1 },
      direction: false,
      type: ShipSizeEnum.M,
      length: 2,
    },
    {
      position: { x: 5, y: 7 },
      direction: true,
      type: ShipSizeEnum.M,
      length: 2,
    },
    {
      position: { x: 6, y: 0 },
      direction: true,
      type: ShipSizeEnum.S,
      length: 1,
    },
    {
      position: { x: 0, y: 3 },
      direction: false,
      type: ShipSizeEnum.S,
      length: 1,
    },
    {
      position: { x: 1, y: 6 },
      direction: true,
      type: ShipSizeEnum.S,
      length: 1,
    },
    {
      position: { x: 9, y: 1 },
      direction: false,
      type: ShipSizeEnum.S,
      length: 1,
    },
  ],
  [
    {
      position: { x: 4, y: 5 },
      direction: true,
      type: ShipSizeEnum.XL,
      length: 4,
    },
    {
      position: { x: 6, y: 5 },
      direction: true,
      type: ShipSizeEnum.L,
      length: 3,
    },
    {
      position: { x: 7, y: 0 },
      direction: true,
      type: ShipSizeEnum.L,
      length: 3,
    },
    {
      position: { x: 0, y: 4 },
      direction: false,
      type: ShipSizeEnum.M,
      length: 2,
    },
    {
      position: { x: 1, y: 0 },
      direction: true,
      type: ShipSizeEnum.M,
      length: 2,
    },
    {
      position: { x: 0, y: 7 },
      direction: false,
      type: ShipSizeEnum.M,
      length: 2,
    },
    {
      position: { x: 8, y: 4 },
      direction: false,
      type: ShipSizeEnum.S,
      length: 1,
    },
    {
      position: { x: 2, y: 9 },
      direction: true,
      type: ShipSizeEnum.S,
      length: 1,
    },
    {
      position: { x: 8, y: 8 },
      direction: false,
      type: ShipSizeEnum.S,
      length: 1,
    },
    {
      position: { x: 5, y: 1 },
      direction: true,
      type: ShipSizeEnum.S,
      length: 1,
    },
  ],
  [
    {
      position: { x: 3, y: 6 },
      direction: false,
      type: ShipSizeEnum.XL,
      length: 4,
    },
    {
      position: { x: 7, y: 0 },
      direction: true,
      type: ShipSizeEnum.L,
      length: 3,
    },
    {
      position: { x: 0, y: 3 },
      direction: false,
      type: ShipSizeEnum.L,
      length: 3,
    },
    {
      position: { x: 3, y: 0 },
      direction: true,
      type: ShipSizeEnum.M,
      length: 2,
    },
    {
      position: { x: 4, y: 3 },
      direction: false,
      type: ShipSizeEnum.M,
      length: 2,
    },
    {
      position: { x: 7, y: 4 },
      direction: false,
      type: ShipSizeEnum.M,
      length: 2,
    },
    {
      position: { x: 0, y: 7 },
      direction: false,
      type: ShipSizeEnum.S,
      length: 1,
    },
    {
      position: { x: 9, y: 0 },
      direction: true,
      type: ShipSizeEnum.S,
      length: 1,
    },
    {
      position: { x: 8, y: 6 },
      direction: false,
      type: ShipSizeEnum.S,
      length: 1,
    },
    {
      position: { x: 9, y: 2 },
      direction: false,
      type: ShipSizeEnum.S,
      length: 1,
    },
  ],
  [
    {
      position: { x: 2, y: 1 },
      direction: false,
      type: ShipSizeEnum.XL,
      length: 4,
    },
    {
      position: { x: 5, y: 6 },
      direction: false,
      type: ShipSizeEnum.L,
      length: 3,
    },
    {
      position: { x: 0, y: 1 },
      direction: true,
      type: ShipSizeEnum.L,
      length: 3,
    },
    {
      position: { x: 3, y: 4 },
      direction: true,
      type: ShipSizeEnum.M,
      length: 2,
    },
    {
      position: { x: 7, y: 0 },
      direction: false,
      type: ShipSizeEnum.M,
      length: 2,
    },
    {
      position: { x: 8, y: 2 },
      direction: true,
      type: ShipSizeEnum.M,
      length: 2,
    },
    {
      position: { x: 0, y: 5 },
      direction: false,
      type: ShipSizeEnum.S,
      length: 1,
    },
    {
      position: { x: 1, y: 8 },
      direction: false,
      type: ShipSizeEnum.S,
      length: 1,
    },
    {
      position: { x: 3, y: 7 },
      direction: false,
      type: ShipSizeEnum.S,
      length: 1,
    },
    {
      position: { x: 9, y: 7 },
      direction: false,
      type: ShipSizeEnum.S,
      length: 1,
    },
  ],
  [
    {
      position: { x: 5, y: 6 },
      direction: false,
      type: ShipSizeEnum.XL,
      length: 4,
    },
    {
      position: { x: 6, y: 1 },
      direction: true,
      type: ShipSizeEnum.L,
      length: 3,
    },
    {
      position: { x: 0, y: 6 },
      direction: false,
      type: ShipSizeEnum.L,
      length: 3,
    },
    {
      position: { x: 6, y: 8 },
      direction: true,
      type: ShipSizeEnum.M,
      length: 2,
    },
    {
      position: { x: 2, y: 3 },
      direction: false,
      type: ShipSizeEnum.M,
      length: 2,
    },
    {
      position: { x: 4, y: 0 },
      direction: true,
      type: ShipSizeEnum.M,
      length: 2,
    },
    {
      position: { x: 0, y: 4 },
      direction: false,
      type: ShipSizeEnum.S,
      length: 1,
    },
    {
      position: { x: 2, y: 8 },
      direction: false,
      type: ShipSizeEnum.S,
      length: 1,
    },
    {
      position: { x: 0, y: 2 },
      direction: false,
      type: ShipSizeEnum.S,
      length: 1,
    },
    {
      position: { x: 0, y: 0 },
      direction: true,
      type: ShipSizeEnum.S,
      length: 1,
    },
  ],
  [
    {
      position: { x: 1, y: 3 },
      direction: false,
      type: ShipSizeEnum.XL,
      length: 4,
    },
    {
      position: { x: 6, y: 3 },
      direction: false,
      type: ShipSizeEnum.L,
      length: 3,
    },
    {
      position: { x: 4, y: 5 },
      direction: false,
      type: ShipSizeEnum.L,
      length: 3,
    },
    {
      position: { x: 0, y: 5 },
      direction: false,
      type: ShipSizeEnum.M,
      length: 2,
    },
    {
      position: { x: 7, y: 0 },
      direction: true,
      type: ShipSizeEnum.M,
      length: 2,
    },
    {
      position: { x: 8, y: 6 },
      direction: false,
      type: ShipSizeEnum.M,
      length: 2,
    },
    {
      position: { x: 0, y: 0 },
      direction: true,
      type: ShipSizeEnum.S,
      length: 1,
    },
    {
      position: { x: 0, y: 8 },
      direction: true,
      type: ShipSizeEnum.S,
      length: 1,
    },
    {
      position: { x: 8, y: 8 },
      direction: true,
      type: ShipSizeEnum.S,
      length: 1,
    },
    {
      position: { x: 2, y: 0 },
      direction: true,
      type: ShipSizeEnum.S,
      length: 1,
    },
  ],
  [
    {
      position: { x: 1, y: 7 },
      direction: false,
      type: ShipSizeEnum.XL,
      length: 4,
    },
    {
      position: { x: 3, y: 1 },
      direction: true,
      type: ShipSizeEnum.L,
      length: 3,
    },
    {
      position: { x: 5, y: 1 },
      direction: true,
      type: ShipSizeEnum.L,
      length: 3,
    },
    {
      position: { x: 7, y: 4 },
      direction: true,
      type: ShipSizeEnum.M,
      length: 2,
    },
    {
      position: { x: 1, y: 2 },
      direction: true,
      type: ShipSizeEnum.M,
      length: 2,
    },
    {
      position: { x: 8, y: 0 },
      direction: true,
      type: ShipSizeEnum.M,
      length: 2,
    },
    {
      position: { x: 1, y: 9 },
      direction: false,
      type: ShipSizeEnum.S,
      length: 1,
    },
    {
      position: { x: 4, y: 5 },
      direction: true,
      type: ShipSizeEnum.S,
      length: 1,
    },
    {
      position: { x: 9, y: 6 },
      direction: false,
      type: ShipSizeEnum.S,
      length: 1,
    },
    {
      position: { x: 0, y: 0 },
      direction: false,
      type: ShipSizeEnum.S,
      length: 1,
    },
  ],
  [
    {
      position: { x: 6, y: 5 },
      direction: true,
      type: ShipSizeEnum.XL,
      length: 4,
    },
    {
      position: { x: 1, y: 4 },
      direction: false,
      type: ShipSizeEnum.L,
      length: 3,
    },
    {
      position: { x: 6, y: 1 },
      direction: false,
      type: ShipSizeEnum.L,
      length: 3,
    },
    {
      position: { x: 8, y: 4 },
      direction: false,
      type: ShipSizeEnum.M,
      length: 2,
    },
    {
      position: { x: 2, y: 1 },
      direction: false,
      type: ShipSizeEnum.M,
      length: 2,
    },
    {
      position: { x: 2, y: 6 },
      direction: true,
      type: ShipSizeEnum.M,
      length: 2,
    },
    {
      position: { x: 0, y: 2 },
      direction: false,
      type: ShipSizeEnum.S,
      length: 1,
    },
    {
      position: { x: 8, y: 7 },
      direction: true,
      type: ShipSizeEnum.S,
      length: 1,
    },
    {
      position: { x: 6, y: 3 },
      direction: true,
      type: ShipSizeEnum.S,
      length: 1,
    },
    {
      position: { x: 0, y: 6 },
      direction: false,
      type: ShipSizeEnum.S,
      length: 1,
    },
  ],
];
